### ISSUE TITLE
rpm creation enhancements

### ISSUE THREAD

**Issue by jacobsalmela** [Cray-HPE/canu#44]
The rpm built from this repo should:

1. build in jenkins
2. appear on the Github Releases page as a downloadable artifact
3. not overwrite user config when installed/upgrade

**Comment by rustydb** [comment]
Also removing `requirements*.txt` files and building a python wheel instead to make things simpler.

**Comment by rustydb** [comment]
I think we should skip number 2, we could but don't need to build an RPM and push to GitHub release. We want that RPM to live with the other CSM-RPMs, that repo is public.

**Comment by rustydb** [comment]
Translating number 1 to "we should build within the spec file."

Number 3 means marking generated files as `%conf` but we might not have expected names for those files.. I'll look into it.
