### ISSUE TITLE
docker image cannot run owing to nornir 3.1.1 / dataclasses 0.8 incompatibility

### ISSUE THREAD

**Issue by dmjacobsen** [Cray-HPE/canu#78]
**Describe the bug**
Cannot start `canu` with no arguments in a docker container built on the `develop` or `release-1.1.4` branch.  The program generates a pair of exceptions indicating an incompatbility between nornir and dataclasses.

**canu Version**
Found this on the `develop` and `release-1.1.4` branches.  Did not try other branches.  Bug prevents program from running, so did not attempt `canu --version`.

**To Reproduce**
1. git clone https://....
2. git checkout develop
3. docker build -t canu .
4. docker run -it canu /bin/bash
5. canu

Then you'll see the errors.

**Expected behavior**
Not crashing and failing and spewing errors.

**Comment by dmjacobsen** [comment]
I found  that by adding:
```
dataclasses==0.7
```
to the top of `requirements.txt` and rebuilding the container, that `canu` can then run (with no arguments) without error.

**Comment by gbaker-hpe** [comment]
Thanks @dmjacobsen.  I spoke with Luke and Sean and they're both going to try to repro this.

**Comment by rustydb** [comment]
I think this can be closed, @dmjacobsen if you see this issue off the current develop branch (1.6.5) please re-open.
