### ISSUE TITLE
Dockerfile assumes use of `docker` or at least privileged container build (not rootless buildah)

### ISSUE THREAD

**Issue by dmjacobsen** [Cray-HPE/canu#80]
**Describe the bug**
NERSC prefers use of rootless containers focused on buildah/podman pipeline (at present).  Use of the `USER canu`, and `chown` prevents build of the container in a rootless environment.  Given I'm unsure of all use-cases this may be expected and needful, however, a solution that also enables rootless build would be appreciated.

**canu Version**
Current `develop` branch.

**To Reproduce**
`buildah bud -t canu .`

**Expected behavior**
Ideally the container would build and then be usable with `podman run -it canu /bin/bash`

**Screenshots**

**Comment by gbaker-hpe** [comment]
Thanks @dmjacobsen.  We'll take a look at this.
